FROM python:3.9-slim 
WORKDIR /app

RUN python -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"

COPY requirements.txt ./
COPY main.py ./
# 
RUN pip install -r requirements.txt

RUN addgroup --system python && \
    adduser --system --disabled-password  --ingroup python python && chown python:python /app
USER python

RUN chown -R python:python /app

CMD ["python", "main.py"]
